name: Workflow for Codecov example-c
on: [push, pull_request]
jobs:
  run-gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile code
        run: gcc -fprofile-arcs -ftest-coverage -O0 -o ieee_oui_downloader ieee_oui_downloader.c -lcurl
      - name: Run tests
        run: ./ieee_oui_downloader
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
